# Metadata for Deliverable 1: Building the Alaska Soil Data Bank

## Data Contributors

-   University of Alaska Fairbanks
-   University of Minnesota
-   National Park Service - Arctic Research Coordination Network (NPS-ACRN)
-   U.S. Army Corps of Engineers Cold Regions Research and Engineering Laborotory (CRREL)
-   Alaska Biological Resarch (ABR, Inc., Anchorage AK)
-   US Department of Energy (DOE)
-   Bureau of Land Management (BLM)
-   US Forest Service (USFS)

## Data Description

\[output from GEMS\]

## Description of Data Mining Procedures

-   hardcopy data
-   digital data

## Standardized Projection

Projection: Alaska Albers NAD83, EPSG: 3338 Scope: Topographic Mapping (small scale) Area of Use: United States (USA) - Alaska Coordinate System: Cartesian 2D CS. Axes: easting, northing (X,Y). Orientations: east, north. Unit: meters (m) Geodetic CRS: NAD83 Datum: North American Datum 1983 Ellipsoid: GRS 1980 Prime meridian: Greenwich Data Source: EPSG Information Source: State of Alaska Department of Natural Resources Revision Date: 11-11-2006

## Data Completeness, Geospatial Data Quality, and Soil Classification Quality Rankings

These rankings will be added to the site (geolocated) metadata for each record. They will be added as field metadata tags in the site id field (data completeness), latitude and longitude fields (geospatial data quality), and classification fields (soil classification quality).

### Data Completeness Rankings

\[From Nic\] These data completeness rankings will be assigned programmatically, but they may still hold value for dataset users who would like a single field to filter all data on:

-   Tier 1 -- Soil morphology and physical/chemical data to a depth of at least 1 meter
-   Tier 2 -- Soil morphology and physical/chemical data to a depth of \< 1m
-   Tier 3 -- Soil morphology to a depth of at least 1m
-   Tier 4 -- Soil morphology to a depth of \< 1m
-   Tier 5 -- Site characteristics only (i.e. thickness of organics, thaw depth, etc)

## Geospatial Data Quality Rankings

\[From Colby\] We took a 'tiered' approach for ranking spatial quality:

-   Tier 1 -- spatial coordinates were noted as being collected with GPS anytime after May 1, 2000 (there is seldom enough information to quantify positional accuracy or the type of GPS, but we figured that coordinates from a GPS unit are probably more consistent than from other sources).
-   Tier 2 -- spatial coordinates were collected post 2010 but not explicitly identified as being collected with GPS. We assume that these were collected with a GPS even if there is nothing that indicates it was collected by GPS.
-   Tier 3 -- spatial coordinates collected between 2000 and 2010 but not explicitly identified as being collected with GPS. Coordinates may have come from a GPS, but it is possible that they were estimated by alternative means.
-   Tier 4 -- pre-2000 GPS (US government agency), if a GPS unit was being used by a US government agency prior to selective availability being turned off (May 1, 2000), it is still likely that the government issued GPS unit was not subject to selective availability, however we cannot be certain.
-   Tier 5 -- pre-2000 GPS (non-US government), even if collected with a GPS, selective availability was turned on before this (it specifically ended May 1, 2000) so quality is suspect.
-   Tier 6 -- pre-2000 Aerial Photo/Topo Annotation, georeferencing was accomplished by annotation of approximate site location on an aerial photo or topographic map.
-   Tier 7 -- pre-2000 Location Description, georeferencing was accomplished by a metes and bounds description of the approximate site location (i.e. 200m NE from the NW corner of section 36 in township and range X and Y).

## Soil Classification Quality Rankings

\[From Nic\] We took a 'tiered' approach for ranking spatial quality:

Soil classification quality rankings will allow users of the database to discern between soil classes which were assigned with varying degrees of uncertainty. Note that the depths of observation and soil physical and chemical properties required to make unambiguous classifications depend on the taxonomic entity in question. For example, if there is permafrost within 1m of the soil surface, no morphology or laboratory data is necessary to make the unambiguous classification to the Gelisol soil order (Tier 1). However, if no other information is available, then classification to the suborder is not possible (Tier 4). This classification certainty ranking is there applied as a field metadata tag to each level of taxonomic classification, which are held in independent fields:

-   Tier 1 -- unambiguous classification; all necessary morphological or soil physical and chemical data are available
-   Tier 2 -- partially ambiguous classification; unambiguous morphological data, but missing some required soil physical or chemical data, few assumptions made regarding soil features and properties
-   Tier 3 -- largely ambiguous classification; morphological data not available to requisite depth or missing key properties, and and/or missing required soil physical or chemical data
-   Tier 4 -- no classification possible; limited morphological data and laboratory data available

There may be other tiers that are worth considering.

## Description of Data Wrangling Procedures-GEMS import

## Description of Controlled Vocabulary/Taxonomy

This project utilizes a project-specific, hierarchical controlled vocabulary or taxonomy (which is crosswalked to NRCS field and laboratory codes where they exist) to tag field metadata. The current version of the controlled vocabulary is in this repository.

## Description of post-ingestion scripting, harmonization procedures

## Description of export procedures
