# Preface {.unnumbered}

This quarto book documents the metadata architecture for "The Alaska Soil Data Bank (ASDB): A database for delivering non-NRCS legacy data for digital soil mapping initiatives in Alaska" - USDA-NRCS SPSD Award #NR223A750025C013.

## Project Description

\[From Project Proposal\] Approximately 300 million acres (\> 70%) of the NOTCOM areas in the United States are in Alaska. Little data is available in unmapped areas of Alaska in the NASIS database. Harnessing disparate non-NRCS legacy datasets for digital soil mapping initiatives in Alaska will therefore be critical for completing the Soils2026 initiative. In order to properly harness big data in soil survey in Alaska, where a significant amount of non-NRCS soil data exists in critical areas, we need to develop a platform that allows public/private data, provides attribution, is flexible and nimble enough to accept ongoing contributions without a large burden on the submitter, can be easily scaled, and can provide export workflows to ingest data into NASIS. The utility of such a database (what we will refer to as the Alaska Soil Data Bank -- ASDB) will be demonstrated through the production of digital soil mapping products at multiple scales and using multiple methods. We will use the harmonized ASDB dataset and NASIS together to produce the first digital statewide predictive map of Alaska soil orders and suborders at 30m resolution, and apply a novel approach to digital soil mapping (using landscape segmentation analysis) for Katmai National Park and Preserve.

## Structure and Deliverables

This document contains metadata for each of the grant deliverables, as well as general project metadata and information. Each of the deliverables also has a unique GitHub repository nested under the alaska-soil-data-bank organization. These deliverables are:

1\. *The Alaska Soil Data Bank (ASDB)*. We will acquire, curate, and centralize non-NRCS legacy data for the state of Alaska and stand up a database for continuing contributions on the G.E.M.S. platform of the University of Minnesota Supercomputing Institute. The ASDB will result in a harmonized dataset for use in digital soil mapping in Alaska and scripts will be written to export the data into a NASIS-readable format for ingestion.

2\. *AK Statewide Predictive Soil Order/Suborder Map*. We will generate digital predictive soil order and soil suborder maps of the state of Alaska at a resolution of 30m.

3\. *Segmentation Analysis Approach to DSM for Katmai National Park and Preserve*. We will utilize a novel landscape segmentation analysis approach to digital soil mapping for Katmai National Park and Preserve.

## Key Personnel

-   Nic Jelinski; Associate Professor, University of Minnesota (PI)
-   Colby Brungard; Associate Professor, New Mexico State University (Co-PI)
-   Sabine Grunwald; Professor, University of Florida (Co-PI);
-   Matt Macander; Senior Scientist, ABR, Inc. (Co-PI)

## Additional Collaborators

-   Sue Ives; Senior Scientist, ABR, Inc.
-   Michael Sousa; Soil Scientist, USDA-NRCS

## Co-Authorship and Data Sharing Agreements

[Co-authorship agreement](co-authorship-template.qmd) [Data Sharing agreement](data-use-and-sharing.qmd)

## Funding Source and RFP

This project was awarded for a proposal submitted to the USDA-NRCS 2022 Soil Science Collaborative Research Proposals RFP

You can find the original RFP here <https://www.grants.gov/web/grants/view-opportunity.html?oppId=337972>.

## Project Website

<https://github.com/alaska-soil-data-bank>
